# Generated by Django 4.2.3 on 2023-07-11 20:51

from django.db import migrations, models

import portal.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoken",
            name="token",
            field=models.CharField(
                default=portal.helpers.generate_token, max_length=255, unique=True
            ),
        ),
    ]
