# Generated by Django 4.2.2 on 2023-07-03 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externaltoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
